# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "wmit/xenial64"
  # config.ssh.insert_key = false
  config.vm.hostname = "xenial"
  # config.vm.box_version = "~> 0.1.0"
  config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
  config.vm.provider :virtualbox do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", 1024]
    # vbox.gui = true
  end
  config.vm.synced_folder "", "/vagrant", create: true
  # config.vm.provision "shell", path: "./pre-puppet.sh"
  config.vm.provision :puppet do |puppet|
    puppet.environment = 'production'
    puppet.environment_path = "puppet/"
    puppet.facter = {
      "environment" => "production",
      "vagrant" => "1",
      "cluster" => "test"
    }
    puppet.hiera_config_path = "puppet/hiera.yaml"
    puppet.options = "--verbose"
  end
  # config.vm.provision "shell", path: "./post-puppet.sh"
end
